#! /bin/sh
### BEGIN INIT INFO
# Provides:		puma
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	puma
# Description:		puma
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/root/.rbenv/shims/puma
MALLOC_ARENA_MAX=2
NAME=puma
DESC=puma

RUNDIR=/root/metasploit-framework
PIDFILE=$RUNDIR/puma.pid
DAEMON_ARGS="-C $RUNDIR/config/puma_production.rb"

test -x $DAEMON || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "

	if start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME start."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "

	if start-stop-daemon --stop --retry KILL/3 --quiet --oknodo --pidfile $PIDFILE
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	sleep 1
	rm -f $PIDFILE
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0