# Generated by Django 3.2.6 on 2023-09-11 03:33

from django.db import migrations, models

import Core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPDomainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdomain', models.CharField(blank=True, max_length=100, null=True)),
                ('type',
                 models.CharField(choices=[('ipaddress', 'ipaddress'), ('domain', 'domain')], default='ipaddress',
                                  max_length=50)),
                ('data', Core.models.DiyDictField(default={})),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PortServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdomain', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=0)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('data', Core.models.DiyDictField(default={})),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdomain', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=0)),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('data', Core.models.DiyDictField(default={})),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebFingerprintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdomain', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.IntegerField(default=0)),
                ('fingerprint', Core.models.DiyDictField(default={})),
                ('data', Core.models.DiyDictField(default={})),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
    ]
