# Generated by Django 4.2 on 2023-09-14 03:05

from django.db import migrations, models

import Core.models


class Migration(migrations.Migration):
    dependencies = [
        ('WebDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdomain', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('data', Core.models.DiyDictField(default={})),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebInfomationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdomain', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.IntegerField(default=0)),
                ('html', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('data', Core.models.DiyDictField(default={})),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='webfingerprintmodel',
            old_name='title',
            new_name='plugin',
        ),
        migrations.RemoveField(
            model_name='webfingerprintmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='webfingerprintmodel',
            name='fingerprint',
        ),
        migrations.AddField(
            model_name='ipdomainmodel',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portservicemodel',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitymodel',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webfingerprintmodel',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
